### ISSUE TITLE
Poladeni tresholdu bran

### ISSUE THREAD

**Issue by msgre** [msgre/europe#17]
Az bude hotov plan, musime vyladit timeouty pro pruchod kulickou.

Mozna to bude v pohode, mozna ne (napadlo me vyradit konkretni branu po pruchodu kulickou na treba 1 vterinu, abychom potlacili ducharinu pri velmi pomalem pruchodu).

**Comment by slintak** [comment]
Timeout na "zákmity" lze nastavit v configu firmware, viz [hardware/src/config.h](https://github.com/msgre/europe/blob/master/hardware/src/config.h#L29). Možná řešení:
1. upravit konstantu na místě podle potřeby a všechny desky aktualizovat přes Modbus,
2. přidat do Modbus registr, kterým pujde tato konstanta nastavit za běhu.
